Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: index.handler
      CodeUri: D:\usr\Victor\Documents\Projects\JavaScript\Angular\reporter\amplify\backend\function\getUser\src
      Runtime: nodejs12.x